# Generated by Django 4.1 on 2023-06-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Post Title')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Post Image')),
                ('short', models.TextField(verbose_name='Short Description')),
                ('full', models.TextField(verbose_name='Full Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
